[package]
name = "pachi-sponsor-precompile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "SponsorHub precompile state machine for Pachi Chain."

[lints]
workspace = true

[features]
test-utils = []

[dependencies]
# pachi
pachi-primitives.workspace = true
pachi-oracle-precompile.workspace = true

# ethereum
alloy-primitives = { workspace = true, features = ["map", "tiny-keccak", "rlp"] }
alloy-rlp = { workspace = true, features = ["arrayvec", "derive"] }

# misc
thiserror.workspace = true

[dev-dependencies]
pachi-oracle-precompile = { workspace = true, features = ["test-utils"] }
