use crate::{PachiTxType, SystemTxSubtype};
use alloy_consensus::Transaction;
use alloy_eips::{eip2930::AccessList, eip7702::SignedAuthorization, Typed2718};
use alloy_primitives::{Address, Bytes, ChainId, TxKind, B256, U256};
use alloy_rlp::{BufMut, Decodable, Encodable, Header};
use pachi_primitives::SYSTEM_ADDRESS;

/// A Pachi system transaction (type 0x50).
///
/// System transactions are unsigned and gas-free. They are generated by the block
/// builder (sequencer) for protocol operations like oracle price updates and VRF
/// fulfillments.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct PachiSystemTx {
    /// Chain ID.
    pub chain_id: ChainId,
    /// System nonce (monotonically increasing).
    pub nonce: u64,
    /// Target address (e.g., Dealer contract for VRF, Oracle state for `OracleUpdate`).
    pub to: Address,
    /// Always 0.
    pub value: U256,
    /// Encoded function call data.
    pub input: Bytes,
    /// Subtype discriminator.
    pub system_tx_type: SystemTxSubtype,
}

impl PachiSystemTx {
    /// Returns the transaction type.
    pub const fn tx_type() -> PachiTxType {
        PachiTxType::System
    }

    /// Returns the system address (sender of system transactions).
    pub const fn sender() -> Address {
        SYSTEM_ADDRESS
    }

    /// Calculates a heuristic for the in-memory size.
    pub fn size(&self) -> usize {
        size_of::<Self>() + self.input.len()
    }

    /// RLP-encodes all fields (without header).
    fn rlp_encoded_fields_length(&self) -> usize {
        self.chain_id.length() +
            self.nonce.length() +
            self.to.length() +
            self.value.length() +
            self.input.0.length() +
            self.system_tx_type.length()
    }

    /// Encodes only the fields (without RLP header).
    fn rlp_encode_fields(&self, out: &mut dyn BufMut) {
        self.chain_id.encode(out);
        self.nonce.encode(out);
        self.to.encode(out);
        self.value.encode(out);
        self.input.0.encode(out);
        self.system_tx_type.encode(out);
    }
}

impl Transaction for PachiSystemTx {
    fn chain_id(&self) -> Option<ChainId> {
        Some(self.chain_id)
    }

    fn nonce(&self) -> u64 {
        self.nonce
    }

    fn gas_limit(&self) -> u64 {
        0
    }

    fn gas_price(&self) -> Option<u128> {
        None
    }

    fn max_fee_per_gas(&self) -> u128 {
        0
    }

    fn max_priority_fee_per_gas(&self) -> Option<u128> {
        None
    }

    fn max_fee_per_blob_gas(&self) -> Option<u128> {
        None
    }

    fn priority_fee_or_price(&self) -> u128 {
        0
    }

    fn effective_gas_price(&self, _base_fee: Option<u64>) -> u128 {
        0
    }

    fn is_dynamic_fee(&self) -> bool {
        false
    }

    fn kind(&self) -> TxKind {
        TxKind::Call(self.to)
    }

    fn is_create(&self) -> bool {
        false
    }

    fn value(&self) -> U256 {
        self.value
    }

    fn input(&self) -> &Bytes {
        &self.input
    }

    fn access_list(&self) -> Option<&AccessList> {
        None
    }

    fn blob_versioned_hashes(&self) -> Option<&[B256]> {
        None
    }

    fn authorization_list(&self) -> Option<&[SignedAuthorization]> {
        None
    }
}

impl Typed2718 for PachiSystemTx {
    fn ty(&self) -> u8 {
        PachiTxType::System as u8
    }
}

impl Encodable for PachiSystemTx {
    fn encode(&self, out: &mut dyn BufMut) {
        Header { list: true, payload_length: self.rlp_encoded_fields_length() }.encode(out);
        self.rlp_encode_fields(out);
    }

    fn length(&self) -> usize {
        let payload_length = self.rlp_encoded_fields_length();
        Header { list: true, payload_length }.length() + payload_length
    }
}

impl Decodable for PachiSystemTx {
    fn decode(buf: &mut &[u8]) -> alloy_rlp::Result<Self> {
        let header = Header::decode(buf)?;
        if !header.list {
            return Err(alloy_rlp::Error::UnexpectedString);
        }
        let remaining = buf.len();

        let this = Self {
            chain_id: Decodable::decode(buf)?,
            nonce: Decodable::decode(buf)?,
            to: Decodable::decode(buf)?,
            value: Decodable::decode(buf)?,
            input: Decodable::decode(buf)?,
            system_tx_type: Decodable::decode(buf)?,
        };

        if buf.len() + header.payload_length != remaining {
            return Err(alloy_rlp::Error::UnexpectedLength);
        }

        Ok(this)
    }
}
